### ISSUE TITLE
Change the name of `wait_list` to `wait_queue_head` in `CondVar`

### ISSUE THREAD

**Issue by BennoLossin** [Rust-for-Linux/linux#1048]
`CondVar` currently has a field called `wait_list`, but its type is `Opaque<bindings::wait_queue_head>`. Change the name to `wait_queue_head` to avoid confusion, since fields that are named `wait_list` normally have the type `struct list_head`.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and so on. Please see https://docs.kernel.org/process/submitting-patches.html and https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel.

**Comment by vobst** [comment]
@AdilDyer are you still working on that one? Otherwise I‘d like to take the opportunity to learn how to submit a patch to the mailing list (never done that before).

@y86-dev In any case I'd be interested what "test your changes" means in this context? Anything besides the things mentioned in the [contributing guidelines](https://rust-for-linux.com/contributing).

Update:
nvm, its already done https://lore.kernel.org/rust-for-linux/20240105012930.1426214-1-charmitro@posteo.net/

**Comment by bjorn3** [comment]
https://lore.kernel.org/rust-for-linux/20240105012930.1426214-1-charmitro@posteo.net/ has been applied in 6b1b2326b2bc3d6a90ec04815130d59ae57f3bc1.
