### ISSUE TITLE
Use docs.kernel.org for documentation links

### ISSUE THREAD

**Issue by ojeda** [Rust-for-Linux/linux#1101]
Sometimes we used www.kernel.org/... links, but it is cleaner and shorter to use docs.kernel.org instead, so we should replace them and be consistent.

---

This requires submitting a proper patch to the LKML and the Rust for Linux mailing list. Please recall to test your changes, to use a proper title for the commit, to sign your commit under the Developer's Certificate of Origin and so on. Please see https://docs.kernel.org/process/submitting-patches.html and https://rust-for-linux.com/contributing for details.

Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

**Comment by jubalh** [comment]
I gave it a try:
https://lore.kernel.org/rust-for-linux/20240820072643.29210-1-jubalh@iodoru.org/T/#u

**Comment by BennoLossin** [comment]
I saw that you already submitted another patch before, have you read the following from above?
> Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.

We of course welcome people contributing stuff, but these small issue are explicitly designed such that new people can make a submission without having to be a coding wizard. So we would appreciate if people only took them for their first contribution and if people are already familiar with the mailing list process, then we would prefer them to do other more advanced development.

(of course if this issue was a lot older, then it can be taken by anyone, but it isn't)

**Comment by jubalh** [comment]
On 8/20/24 10:13, y86-dev wrote:> I saw that you already submitted another patch before, have you read the following from above?
Yep I read that.

>> Please take this issue only if you are new to the kernel development process and you would like to use it as a test to submit your first patch to the kernel. Please do not take it if you do not plan to make other contributions to the kernel.
> 
> We of course welcome people contributing stuff, but these small issue are explicitly designed such that new people can make a submission without having to be a coding wizard. So we would appreciate if people only took them for their first contribution and if people are already familiar with the mailing list process, then we would prefer them to do other more advanced development.
> 
> (of course if this issue was a lot older, then it can be taken by anyone, but it isn't)
Well basically this is my first time working via mailing lists. And I'm still trying to figure out the whole process. Plenty of questions in my head how something is done and noone to ask :)

So I figured I'm exactly the kind of person the message above speaks to: someone who wants to get into Kernel (and Rust) development with no experience in these nor with the workflow.

It is true though that this is my 2nd patch, the first one just being sent yesterday (where I am still unsure if everything is expected so I wanted to go through the process again today to confirm its right and to get used to it).

**Comment by BennoLossin** [comment]
> Well basically this is my first time working via mailing lists. And I'm still trying to figure out the whole process. Plenty of questions in my head how something is done and noone to ask :)

Oh I see, my bad then. I assumed that you already had some experience, since your first patch was for something that we didn't have a good-first-issue for. If you have questions, feel free to ask them on our [zulip](https://rust-for-linux.zulipchat.com/).

> So I figured I'm exactly the kind of person the message above speaks to: someone who wants to get into Kernel (and Rust) development with no experience in these nor with the workflow.

Yeah that is how they are intended.

> It is true though that this is my 2nd patch, the first one just being sent yesterday (where I am still unsure if everything is expected so I wanted to go through the process again today to confirm its right and to get used to it).

From what I can see, you did everything right, you also got Alice's and my review already :)

**Comment by ojeda** [comment]
Applied to `rust-next` -- thanks everyone!
