### ISSUE TITLE
FYI: lrs is an alternative rust stdlib without panics, handles allocation failures

### ISSUE THREAD

**Issue by kosta** [Rust-for-Linux/linux#198]
Hi!

Re: [PATCH 07/13] Rust: Kernel crate
@ojeda wrote in https://lkml.org/lkml/2021/4/14/1106
> However, we will be
> customizing/rewriting `alloc` as needed to customize its types (things
> like `Box`, `Vec`, etc.) so that we can do things like pass allocation
> flags, ensure we always have fallible allocations, perhaps reuse some
> of the kernel data structures, etc.

Just FYI: In 2015/2016 someone wrote a rust std lib that never panics and returns allocation failures as Results. (Seems like development stopped in 2016). 

No idea how usable that is for your use case.

Code is here https://github.com/lrs-lang/lib

Example: docs for Vec::try_push: 
http://lrs-lang.github.io/pages/doc/lrs::vec::Vec::try_push.html

Code is MPL 2.0 which I think is GPL 2 compatible, but IANAL.

Feel free to close if this is not interesting.

Cheers,
Kosta

**Comment by bjorn3** [comment]
Lrs hasn't been updated for over 5 years. It completely replaces libcore too. Given that libcore is intrinsically tied to the exact rustc version, this means that it won't work with any rustc version from not too long since it's last update. Writing a liballoc alternative on top of the official libcore is going to be much less work than trying to adapt lrs and it will continue to work for as long as it doesn't use any unstable features.

**Comment by alex** [comment]
Indeed.Thanks for the heads up, but I don't thinklrs is a fruitful direction for us.
