### ISSUE TITLE
Coding and style guidelines

### ISSUE THREAD

**Issue by soruh** [Rust-for-Linux/linux#256]
There are quite a few things in Rust where there are several ways to achieve the same thing. Should there be a uniform style (e.g. in `style.rst` or inline in `coding.rst`) or should everyone just do it their own way?

Such style choices could include (but are not limited to):
- `Arc::clone(x)` vs `x.clone()`
- `#[repr(type)] enum`s vs `const`ants
```rust
#[repr(u32)]
enum Foo {
    A = 1,
    B = 2
}
// or
const FOO_A: u32 = 1;
const FOO_B: u32 = 2;
```
- `String::from()` vs `.to_owned()` vs `.clone()` (although this may be decided by the fallible allocation API anyways)
- `From` over `Into`
```rust
function(x.into())
// or
function(Foo::from(x))
```
- should code generally have to pass `cargo clippy` and at which settings?
- `slice.get(i)` vs explicit bounds check + `slice[i]`
- `as *const _` vs `.cast()` ([clippy stance](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_as_ptr))

**Comment by soruh** [comment]
~~I seem to have pressed ctrl+enter, please disregard this issue until I update it.~~

**Comment by ojeda** [comment]
Yeah, I am in the process of writing a fairly extensive update of `Doc/rust/coding.rst` etc. with many of the bits we have collected so far from reviews, discussions, etc. In particular, custom rules, conventions and annotations we follow in the kernel are the most important ones, but I have also added a few general style guidelines too.

**Comment by soruh** [comment]
That's great, is there a way to contribute to that / add to the discussion of what style should be adopted?

**Comment by ojeda** [comment]
Sure! In general, we have been discussing these things as they appear in PRs etc. The most direct way would be instead to review the PR I will send (please do so if you have free time!). Another avenue is the meetings etc.

**Comment by ojeda** [comment]
Updates: nowadays we have `coding-guidelines.rst` (and other docs) where we are still deciding/adding things from time to time as they get discussed when upstreaming other bits. Nowadays we require passing `CLIPPY=1` for upstreaming, and there have been discussions about enabling more lints, so some of these may be enforceable via Clippy (and we regularly suggest new lints to Clippy too).

By the way, concerning the question in the issue:

> Should there be a uniform style

The answer is yes -- one of the things we are trying to do with Rust in the kernel is enforcing a uniform style and be consistent as much as possible, since now is the best time to do so (i.e. when everything is being upstreamed). However, we should only do so where it makes sense, and we may need to be flexible sometimes.

To discuss particular lints/guidelines, it is probably best to use Zulip nowadays (we use issues now to track things/features/ideas that are mostly decided and bugs). Of course, please feel free to send patches/RFCs to the mailing list too. If issues are needed, it is probably best to create specific ones / more targeted.

Thanks!
