### ISSUE TITLE
Provide an interface to access raw pointer in `UserSlicePtr`

### ISSUE THREAD

**Issue by avalon1610** [Rust-for-Linux/linux#867]
I'm working with a third-party module which use `_IOWR` incorrectly by specific a wrong size (given an ptr size), and I cannot fix this. This cause I can not pass the length checking in `write_raw` when passing data to userspace.

Could you provide an interface to access private field `*mut core::ffi::c_void` so I can handle `binings::copy_to_user` by myself?

**Comment by ojeda** [comment]
What is the reason why it cannot be fixed in the third-party module?

**Comment by avalon1610** [comment]
It's a vendor's private module and I think they might need to keep it forward compatible. I can't get them to fix this anyway.  
Providing such an interface (should be unsafe) might help the user to deal with this situation.

**Comment by ojeda** [comment]
So, it sounds like the one you cannot fix is an out-of-tree, likely proprietary module, right?

Having the `unsafe fn` would be technically fine and maybe we end up with it anyway for other reasons, but we should be able to justify the code we have is not dead with upstream users. For that, an out-of-tree module using it to workaround an issue in another out-of-tree module is not the best justification; and much less so if we do not even have access to the code.

In addition, please note that if your module is using symbols from a proprietary one, then your module is also to be considered proprietary, and therefore in that case your module shouldn't be using the Rust support since it is not exported for non-GPL compatible modules.

@gregkh

**Comment by ojeda** [comment]
Closing -- there does not seem anything to do here.
